### ISSUE TITLE
How to generate the 'Synthetic Data'?

### ISSUE THREAD

**Issue by tanganke** [amirbar/visual_prompting#4]
How can I generate the synthetic dataset described at section 4.3? 
![image](https://user-images.githubusercontent.com/33046358/221507978-1a7ede8a-552a-44b8-9398-3f39808d64fd.png)

**Comment by amirbar** [comment]
It is present here:
https://github.com/amirbar/visual_prompting/blob/main/evaluate/reasoning_dataloader.py
